
   INFO  Running migrations.  

  2025_01_07_113555_create_tuotes_table ......................................  
  ⇂ create table `tuotes` (`id` bigint unsigned not null auto_increment primary key, `nimi` varchar(255) not null, `kuvaus` text null, `hinta` decimal(8, 2) not null, `varastossa` int not null default '0', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  2025_01_07_142318_create_myyja_table .......................................  
  ⇂ create table `myyja` (`myyjaID` bigint unsigned not null auto_increment primary key, `nimi` varchar(255) not null, `kayttajatunnus` varchar(255) not null, `salasana` varchar(255) not null, `rooli` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  ⇂ alter table `myyja` add unique `myyja_kayttajatunnus_unique`(`kayttajatunnus`)  
  2025_01_09_171951_create_asiakas_table .....................................  
  ⇂ create table `asiakas` (`id` bigint unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  2025_01_09_171951_create_tuote_table .......................................  
  ⇂ create table `tuote` (`id` bigint unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  2025_01_09_171952_create_vuokraus_table ....................................  
  ⇂ create table `vuokraus` (`id` bigint unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  2025_01_09_171952_create_vuokrausrivi_table ................................  
  ⇂ create table `vuokrausrivi` (`id` bigint unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  

